// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/index": typeof import("./src/routes/index.tsx");
};