// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/legal": {
    params: {};
  };
  "/legal/privacy": {
    params: {};
  };
  "/legal/eula": {
    params: {};
  };
  "/plan-preview": {
    params: {};
  };
  "/plan-preview/:recordUri": {
    params: {
      "recordUri": string;
    };
  };
  "/events": {
    params: {};
  };
  "/demo": {
    params: {};
  };
  "/templates": {
    params: {};
  };
  "/templates/:templateKey": {
    params: {
      "templateKey": string;
    };
  };
  "/projects": {
    params: {};
  };
  "/projects/:projectId": {
    params: {
      "projectId": string;
    };
  };
  "/customers": {
    params: {};
  };
  "/customers/:customerId": {
    params: {
      "customerId": string;
    };
  };
  "/tasks": {
    params: {};
  };
  "/tasks/kanban": {
    params: {};
  };
  "/integrations": {
    params: {};
  };
  "/ingest": {
    params: {};
  };
  "/workspaces": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/legal" | "/legal/privacy" | "/legal/eula" | "/plan-preview" | "/plan-preview/:recordUri" | "/events" | "/demo" | "/templates" | "/templates/:templateKey" | "/projects" | "/projects/:projectId" | "/customers" | "/customers/:customerId" | "/tasks" | "/tasks/kanban" | "/integrations" | "/ingest" | "/workspaces" | "/users" | "/*";
  };
  "routes/legal-layout.tsx": {
    id: "routes/legal-layout";
    page: "/legal" | "/legal/privacy" | "/legal/eula";
  };
  "routes/legal-privacy.tsx": {
    id: "routes/legal-privacy";
    page: "/legal/privacy";
  };
  "routes/legal-eula.tsx": {
    id: "routes/legal-eula";
    page: "/legal/eula";
  };
  "routes/root.tsx": {
    id: "routes/root";
    page: "/" | "/plan-preview" | "/plan-preview/:recordUri" | "/events" | "/demo" | "/templates" | "/templates/:templateKey" | "/projects" | "/projects/:projectId" | "/customers" | "/customers/:customerId" | "/tasks" | "/tasks/kanban" | "/integrations" | "/ingest" | "/workspaces" | "/users" | "/*";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/plan-preview.tsx": {
    id: "routes/plan-preview";
    page: "/plan-preview";
  };
  "routes/plan-preview-record.tsx": {
    id: "routes/plan-preview-record";
    page: "/plan-preview/:recordUri";
  };
  "routes/events.tsx": {
    id: "routes/events";
    page: "/events";
  };
  "routes/demo.tsx": {
    id: "routes/demo";
    page: "/demo";
  };
  "routes/templates.tsx": {
    id: "routes/templates";
    page: "/templates";
  };
  "routes/templates-template.tsx": {
    id: "routes/templates-template";
    page: "/templates/:templateKey";
  };
  "routes/projects.tsx": {
    id: "routes/projects";
    page: "/projects";
  };
  "routes/projects-project.tsx": {
    id: "routes/projects-project";
    page: "/projects/:projectId";
  };
  "routes/customers.tsx": {
    id: "routes/customers";
    page: "/customers";
  };
  "routes/customers-customer.tsx": {
    id: "routes/customers-customer";
    page: "/customers/:customerId";
  };
  "routes/tasks.tsx": {
    id: "routes/tasks";
    page: "/tasks";
  };
  "routes/tasks-kanban.tsx": {
    id: "routes/tasks-kanban";
    page: "/tasks/kanban";
  };
  "routes/integrations.tsx": {
    id: "routes/integrations";
    page: "/integrations";
  };
  "routes/ingest.tsx": {
    id: "routes/ingest";
    page: "/ingest";
  };
  "routes/workspaces.tsx": {
    id: "routes/workspaces";
    page: "/workspaces";
  };
  "routes/users.tsx": {
    id: "routes/users";
    page: "/users";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/legal-layout": typeof import("./src/routes/legal-layout.tsx");
  "routes/legal-privacy": typeof import("./src/routes/legal-privacy.tsx");
  "routes/legal-eula": typeof import("./src/routes/legal-eula.tsx");
  "routes/root": typeof import("./src/routes/root.tsx");
  "routes/index": typeof import("./src/routes/index.tsx");
  "routes/plan-preview": typeof import("./src/routes/plan-preview.tsx");
  "routes/plan-preview-record": typeof import("./src/routes/plan-preview-record.tsx");
  "routes/events": typeof import("./src/routes/events.tsx");
  "routes/demo": typeof import("./src/routes/demo.tsx");
  "routes/templates": typeof import("./src/routes/templates.tsx");
  "routes/templates-template": typeof import("./src/routes/templates-template.tsx");
  "routes/projects": typeof import("./src/routes/projects.tsx");
  "routes/projects-project": typeof import("./src/routes/projects-project.tsx");
  "routes/customers": typeof import("./src/routes/customers.tsx");
  "routes/customers-customer": typeof import("./src/routes/customers-customer.tsx");
  "routes/tasks": typeof import("./src/routes/tasks.tsx");
  "routes/tasks-kanban": typeof import("./src/routes/tasks-kanban.tsx");
  "routes/integrations": typeof import("./src/routes/integrations.tsx");
  "routes/ingest": typeof import("./src/routes/ingest.tsx");
  "routes/workspaces": typeof import("./src/routes/workspaces.tsx");
  "routes/users": typeof import("./src/routes/users.tsx");
  "routes/not-found": typeof import("./src/routes/not-found.tsx");
};