-- Migration number: 0002 	 2026-01-16T17:20:52.550Z
-- events
--
-- Append-only event log for all external and internal triggers.
--
-- This table is the backbone of reliability and idempotency.
-- Every integration (QuickBooks, Shopify, manual actions) is normalized
-- into an event and processed through the same pipeline.
--
-- Key guarantees:
--   - Each semantic event is processed at most once (via idempotency_key)
--   - Raw payloads are preserved for debugging and replay
--   - Processing is auditable and time-ordered
--
-- IMPORTANT:
--   Application code must NEVER update or delete rows in this table,
--   except to set processed_at / process_error.

CREATE TABLE IF NOT EXISTS events (
  -- Internal UUID for the event (generated by the system)
  id TEXT PRIMARY KEY,

  -- Source system that produced the event
  -- Examples: 'qbo', 'shopify', 'manual', 'system'
  source TEXT NOT NULL,

  -- Semantic event type
  -- Examples: 'payment_applied', 'order_paid', 'project_created'
  type TEXT NOT NULL,

  -- Stable identifier from the source system
  -- Examples: QuickBooks payment_id, Shopify order_id
  -- May be NULL for purely internal/system events
  external_id TEXT,

  -- Deterministic unique key used for idempotency
  -- Format: <source>:<type>:<external_id>
  idempotency_key TEXT NOT NULL,

  -- Raw JSON payload from the source system
  -- Stored verbatim for debugging and replay
  payload TEXT NOT NULL,

  -- ISO-8601 timestamp when the event was received by the system
  received_at TEXT NOT NULL,

  -- ISO-8601 timestamp when processing completed successfully
  processed_at TEXT,

  -- Error message from the last failed processing attempt (if any)
  process_error TEXT
);

-- Enforce idempotency at the database level.
-- Any attempt to insert a duplicate idempotency_key will fail.
CREATE UNIQUE INDEX IF NOT EXISTS events_idempotency_idx
ON events (idempotency_key);

-- Optional index to support querying by source/type and time.
-- Useful for debugging, replay, and operational visibility.
CREATE INDEX IF NOT EXISTS events_source_type_idx
ON events (source, type, received_at);
